/* ordo.earth — marketing site behaviour (pages generated by scripts/build-site.mjs). */
(function () {
  'use strict';

  var reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var $ = function (sel, root) { return (root || document).querySelector(sel); };
  var $$ = function (sel, root) { return Array.prototype.slice.call((root || document).querySelectorAll(sel)); };
  var params = new URLSearchParams(location.search);

  $$('[data-year]').forEach(function (el) { el.textContent = new Date().getFullYear(); });

  // ─── Header: shadow, hide-on-scroll, progress bar ─────────────────────
  var header = $('#siteHeader');
  var menuBtn = $('.menu-btn');
  var menu = $('#mobileMenu');
  if (header) {
    var lastY = window.scrollY, ticking = false;
    var onScroll = function () {
      var y = window.scrollY;
      var max = document.documentElement.scrollHeight - window.innerHeight;
      header.classList.toggle('is-scrolled', y > 8);
      var menuOpen = menuBtn && menuBtn.getAttribute('aria-expanded') === 'true';
      if (!menuOpen && !header.contains(document.activeElement)) {
        if (y > 420 && y - lastY > 6) header.classList.add('is-hidden');
        else if (lastY - y > 6 || y < 420) header.classList.remove('is-hidden');
      }
      header.style.setProperty('--progress', max > 0 ? Math.min(1, y / max).toFixed(4) : 0);
      lastY = y;
      ticking = false;
    };
    window.addEventListener('scroll', function () {
      if (!ticking) { ticking = true; requestAnimationFrame(onScroll); }
    }, { passive: true });
    header.addEventListener('focusin', function () { header.classList.remove('is-hidden'); });
    onScroll();
  }

  // ─── Mobile menu ──────────────────────────────────────────────────────
  if (menuBtn && menu) {
    var setMenu = function (open) {
      menuBtn.setAttribute('aria-expanded', String(open));
      menuBtn.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
      menu.hidden = !open;
      menu.classList.toggle('is-open', open);
    };
    menuBtn.addEventListener('click', function () { setMenu(menuBtn.getAttribute('aria-expanded') !== 'true'); });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && !menu.hidden) { setMenu(false); menuBtn.focus(); }
    });
    window.matchMedia('(min-width: 1021px)').addEventListener('change', function (m) { if (m.matches) setMenu(false); });
  }

  // ─── Scroll reveals (print-in images, headings, copy, process) ────────
  var revealSel = '[data-split], [data-reveal], [data-print], [data-steps]';
  if (reduceMotion || !('IntersectionObserver' in window)) {
    $$(revealSel).forEach(function (el) { el.classList.add('is-in'); });
  } else {
    var io = new IntersectionObserver(function (entries) {
      // Elements entering together (a grid row) print one after another.
      var n = 0;
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        var el = entry.target;
        if (el.hasAttribute('data-print')) el.style.setProperty('--stagger', (n++ * 140) + 'ms');
        el.classList.add('is-in');
        io.unobserve(el);
      });
    }, { rootMargin: '0px 0px -12% 0px', threshold: 0.12 });
    $$(revealSel).forEach(function (el) { io.observe(el); });
  }

  // ─── Hero carousel ────────────────────────────────────────────────────
  var hero = $('[data-carousel]');
  if (hero) {
    var slides = $$('.slide', hero);
    var dots = $$('[data-goto]', hero);
    var toggle = $('[data-toggle]', hero);
    var live = $('.slides', hero);
    var DURATION = 7000;
    var current = 0, elapsed = 0, last = 0, raf = 0;
    var userPaused = reduceMotion, hoverHold = false, onScreen = true;

    var setProgress = function () {
      dots.forEach(function (d, i) {
        var p = i !== current ? 0 : reduceMotion ? 1 : elapsed / DURATION;
        d.style.setProperty('--p', Math.min(1, p).toFixed(4));
      });
    };

    var running = function () { return !userPaused && !hoverHold && onScreen && !document.hidden; };

    var tick = function (now) {
      raf = 0;
      if (!running()) return;
      elapsed += Math.min(now - last, 100); // a throttled frame never skips a slide
      last = now;
      if (elapsed >= DURATION) go(current + 1);
      setProgress();
      raf = requestAnimationFrame(tick);
    };

    var sync = function () {
      if (running() && !raf) { last = performance.now(); raf = requestAnimationFrame(tick); }
    };

    var go = function (next, fromUser) {
      next = (next + slides.length) % slides.length;
      if (next === current) return;
      hero.classList.remove('is-initial');
      // announce only changes the visitor asked for, not auto-rotation
      live.setAttribute('aria-live', fromUser ? 'polite' : 'off');
      var prev = slides[current];
      prev.classList.remove('is-active');
      prev.classList.add('is-leaving');
      prev.setAttribute('aria-hidden', 'true');
      prev.inert = true;
      setTimeout(function () { prev.classList.remove('is-leaving'); }, 700);
      current = next;
      var cur = slides[current];
      cur.removeAttribute('aria-hidden');
      cur.inert = false;
      void cur.offsetWidth; // restart CSS animations on re-entry
      cur.classList.add('is-active');
      dots.forEach(function (d, i) {
        if (i === current) d.setAttribute('aria-current', 'true');
        else d.removeAttribute('aria-current');
      });
      elapsed = 0;
      setProgress();
    };

    var setPaused = function (paused) {
      userPaused = paused;
      hero.classList.toggle('is-paused', paused);
      toggle.setAttribute('aria-label', paused ? 'Play rotation' : 'Pause rotation');
      setProgress();
      sync();
    };

    dots.forEach(function (d) { d.addEventListener('click', function () { go(+d.dataset.goto, true); }); });
    $('[data-prev]', hero).addEventListener('click', function () { go(current - 1, true); });
    $('[data-next]', hero).addEventListener('click', function () { go(current + 1, true); });
    toggle.addEventListener('click', function () { setPaused(!userPaused); });
    hero.addEventListener('pointerenter', function (e) { if (e.pointerType === 'mouse') hoverHold = true; });
    hero.addEventListener('pointerleave', function () { hoverHold = false; sync(); });
    hero.addEventListener('focusin', function () { hoverHold = true; });
    hero.addEventListener('focusout', function (e) { if (!hero.contains(e.relatedTarget)) { hoverHold = false; sync(); } });
    document.addEventListener('visibilitychange', sync);
    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (en) { onScreen = en[0].isIntersecting; sync(); }).observe(hero);
    }

    // swipe between ranges on touch screens
    var sx = null, sy = null;
    hero.addEventListener('touchstart', function (e) { sx = e.touches[0].clientX; sy = e.touches[0].clientY; }, { passive: true });
    hero.addEventListener('touchend', function (e) {
      if (sx === null) return;
      var dx = e.changedTouches[0].clientX - sx, dy = e.changedTouches[0].clientY - sy;
      if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) go(current + (dx < 0 ? 1 : -1), true);
      sx = null;
    });

    setPaused(userPaused);
  }

  // ─── Ranges filter (FLIP-animated grid) ───────────────────────────────
  var ranges = $('[data-ranges]');
  if (ranges) {
    var grid = $('[data-grid]', ranges);
    var cards = $$('.pcard', grid);
    var countEl = $('[data-count]', ranges);
    var emptyEl = $('[data-empty]', ranges);
    var appGroup = $('.fgroup-app', ranges);
    var state = {
      range: params.get('range') || '',
      collection: params.get('collection') || '',
      application: params.get('application') || '',
    };

    var matches = function (c) {
      return (!state.range || c.dataset.range === state.range) &&
        (!state.collection || c.dataset.collections.split(' ').indexOf(state.collection) > -1) &&
        (!state.application || c.dataset.applications.split(' ').indexOf(state.application) > -1);
    };

    var syncChips = function () {
      $$('.fchip', ranges).forEach(function (b) {
        b.setAttribute('aria-pressed', String(state[b.dataset.filter] === b.dataset.value));
      });
      appGroup.hidden = !state.application;
    };

    var apply = function (animate) {
      var before = new Map();
      if (animate && !reduceMotion) cards.forEach(function (c) { if (!c.classList.contains('is-out')) before.set(c, c.getBoundingClientRect()); });
      var n = 0;
      cards.forEach(function (c) { var ok = matches(c); c.classList.toggle('is-out', !ok); if (ok) n++; });
      emptyEl.hidden = n > 0;
      if (countEl.textContent !== String(n)) {
        countEl.textContent = n;
        countEl.classList.remove('bump'); void countEl.offsetWidth; countEl.classList.add('bump');
      }
      countEl.parentNode.lastChild.textContent = n === 1 ? ' product idea' : ' product ideas';
      syncChips();
      if (!animate || reduceMotion) return;
      cards.forEach(function (c, i) {
        if (c.classList.contains('is-out')) return;
        var a = before.get(c), b = c.getBoundingClientRect();
        if (a) {
          var dx = a.left - b.left, dy = a.top - b.top;
          if (dx || dy) c.animate([{ transform: 'translate(' + dx + 'px,' + dy + 'px)' }, { transform: 'none' }], { duration: 550, easing: 'cubic-bezier(.16,1,.3,1)' });
        } else {
          c.animate([{ opacity: 0, transform: 'translateY(18px) scale(.96)' }, { opacity: 1, transform: 'none' }], { duration: 500, delay: Math.min(i, 8) * 35, easing: 'cubic-bezier(.16,1,.3,1)', fill: 'backwards' });
        }
      });
    };

    var writeUrl = function () {
      var q = new URLSearchParams();
      Object.keys(state).forEach(function (k) { if (state[k]) q.set(k, state[k]); });
      history.replaceState(null, '', location.pathname + (q.toString() ? '?' + q : ''));
    };

    ranges.addEventListener('click', function (e) {
      var chip = e.target.closest('.fchip');
      if (chip) {
        var k = chip.dataset.filter;
        state[k] = state[k] === chip.dataset.value && k === 'application' ? '' : chip.dataset.value;
        // a sub-collection only exists within Ordo Collections
        if (k === 'collection' && state.collection && state.range && state.range !== 'ordo-collections') state.range = '';
        if (k === 'range' && state.range && state.range !== 'ordo-collections') state.collection = '';
      } else if (e.target.closest('[data-clear-app]')) {
        state.application = '';
      } else if (e.target.closest('[data-clear-all]')) {
        state.range = state.collection = state.application = '';
      } else return;
      apply(true);
      writeUrl();
    });

    apply(false);
  }

  // ─── Product gallery ──────────────────────────────────────────────────
  $$('[data-gallery]').forEach(function (g) {
    var imgs = $$('.gallery-main img', g);
    var btns = $$('[data-view]', g);
    btns.forEach(function (b) {
      b.addEventListener('click', function () {
        var i = +b.dataset.view;
        imgs.forEach(function (im, j) { im.classList.toggle('is-active', i === j); });
        btns.forEach(function (x) { x.setAttribute('aria-pressed', String(x === b)); });
      });
    });
  });

  // ─── WhatsApp links carry the enquiry context ─────────────────────────
  var context = params.get('product') || params.get('interest');
  $$('[data-wa]').forEach(function (a) {
    var text = context ? 'Hi Ordo, I’d like to discuss ' + context + '.' : 'Hi Ordo, I’d like to discuss a project.';
    a.href = a.href.split('?')[0] + '?text=' + encodeURIComponent(text);
  });

  // ─── Enquiry form ─────────────────────────────────────────────────────
  var form = $('#enquiryForm');
  if (form) {
    var wrap = form.closest('.enquiry');
    var done = $('.form-done', wrap);
    var status = $('.form-status', form);
    var submit = $('button[type="submit"]', form);

    var interest = params.get('interest');
    if (interest && $$('option', form.interest).some(function (o) { return o.value === interest; })) form.interest.value = interest;
    if (params.get('message')) form.message.value = params.get('message');
    if (params.get('product')) form.product.value = params.get('product');

    var messages = {
      name: 'Enter your name.',
      email: 'Enter a valid email address, like name@company.com.',
      interest: 'Choose what you’re interested in.',
      message: 'Add a short message about your project.',
    };

    var setError = function (name, msg) {
      var input = form.elements[name];
      var field = input.closest('.field');
      var err = $('.field-error', field);
      if (!msg) {
        input.removeAttribute('aria-invalid');
        input.removeAttribute('aria-describedby');
        if (err) err.remove();
        return;
      }
      if (!err) {
        err = document.createElement('p');
        err.className = 'field-error';
        err.id = 'err-' + name;
        field.appendChild(err);
      }
      err.textContent = msg;
      input.setAttribute('aria-invalid', 'true');
      input.setAttribute('aria-describedby', err.id);
    };

    var check = function (name) {
      var v = form.elements[name].value.trim();
      var bad = name === 'email' ? !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v) : name === 'message' ? v.length < 5 : !v;
      setError(name, bad ? messages[name] : '');
      return !bad;
    };

    Object.keys(messages).forEach(function (name) {
      var el = form.elements[name];
      el.addEventListener('blur', function () { if (el.value.trim() || el.hasAttribute('aria-invalid')) check(name); });
      el.addEventListener('input', function () { if (el.hasAttribute('aria-invalid')) check(name); });
    });

    form.addEventListener('submit', function (e) {
      e.preventDefault();
      var bad = Object.keys(messages).filter(function (n) { return !check(n); });
      if (bad.length) {
        status.className = 'form-status is-error';
        status.textContent = bad.length === 1 ? 'Check the highlighted field.' : 'Check the ' + bad.length + ' highlighted fields.';
        form.elements[bad[0]].focus();
        return;
      }
      var payload = {};
      ['name', 'company', 'email', 'phone', 'interest', 'message', 'product', 'website'].forEach(function (k) {
        payload[k] = form.elements[k].value.trim();
      });
      payload.t = Math.round(performance.now()); // time on page; the server drops instant bot posts
      submit.disabled = true;
      submit.querySelector('span').textContent = 'Sending…';
      status.className = 'form-status';
      status.textContent = '';

      fetch('/api/enquiry', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
        .then(function (res) { return res.json().catch(function () { return {}; }).then(function (d) { return { ok: res.ok, data: d }; }); })
        .then(function (r) {
          if (!r.ok) {
            if (r.data.field && messages[r.data.field]) { setError(r.data.field, r.data.error); form.elements[r.data.field].focus(); }
            throw new Error(r.data.error || 'Your enquiry wasn’t sent. Try again, or message us on WhatsApp at +60 10-792 4208.');
          }
          $('[data-done-email]', done).textContent = payload.email;
          $('[data-done-ref]', done).textContent = r.data.enquiry_id;
          form.hidden = true;
          done.hidden = false;
          wrap.classList.add('is-sent');
          done.focus();
        })
        .catch(function (err) {
          status.className = 'form-status is-error';
          status.textContent = err.message && err.message !== 'Failed to fetch' ? err.message : 'You appear to be offline. Check your connection and try again.';
        })
        .then(function () {
          submit.disabled = false;
          submit.querySelector('span').textContent = 'Send enquiry';
        });
    });

    $('[data-reset]', done).addEventListener('click', function () {
      form.reset();
      done.hidden = true;
      form.hidden = false;
      wrap.classList.remove('is-sent');
      form.elements.name.focus();
    });
  }
})();
