// Bundles entry.jsx (React + ReactDOM + OrdoAdmin.jsx) into a single minified
// IIFE with esbuild, then writes it out as ../functions/admin/manage-bundle.js
// — a Pages Function that just serves that JS as a static-ish response.
//
// Run: npm install && npm run build
// Then commit the regenerated functions/admin/manage-bundle.js alongside your
// OrdoAdmin.jsx changes.

const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const result = esbuild.buildSync({
  entryPoints: [path.join(__dirname, "entry.jsx")],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2019",
  write: false,
  loader: { ".jsx": "jsx" },
});

const code = result.outputFiles[0].text;

const out = `// AUTO-GENERATED by admin-manage/build.js — do not edit directly.
// Source: admin-manage/OrdoAdmin.jsx + admin-manage/entry.jsx
// Regenerate with: cd admin-manage && npm install && npm run build

const BUNDLE = ${JSON.stringify(code)};

export async function onRequestGet() {
  return new Response(BUNDLE, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
`;

const outPath = path.join(__dirname, "..", "functions", "admin", "manage-bundle.js");
fs.writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${(code.length / 1024).toFixed(1)} KB bundle)`);
