import React, { useState, useEffect, useCallback } from "react";

// ---------- constants ----------
const STORAGE_KEY = "ordo-core-v1";

const STATUS_FLOW = [
  "Lead",
  "Quotation Sent",
  "PO Confirmed",
  "In Production",
  "Delivered",
  "Paid",
];
const STATUS_COLORS = {
  Lead: "#8A8F98",
  "Quotation Sent": "#D9A404",
  "PO Confirmed": "#2F6FED",
  "In Production": "#E8600C",
  Delivered: "#7B5FE0",
  Paid: "#1B8A6B",
  Cancelled: "#C23B3B",
};
const DOC_PREFIX = { Quotation: "QT", Invoice: "INV", Receipt: "RCT" };

const defaultCore = () => ({
  users: [
    { name: "Nabilah", pin: "1234" },
    { name: "Azan", pin: "1234" },
    { name: "Dayana", pin: "1234" },
    { name: "Firdaus", pin: "1234" },
  ],
  companyInfo: {
    name: "Ordo",
    tagline: "3D Printing Studio",
    address: "",
    phone: "",
    email: "",
    bankDetails: "",
  },
  assumptions: {
    filamentCostPerKg: 50,
    electricityRate: 0.3,
    printerPrice: 3000,
    printerLifetimeHrs: 5000,
    printerPowerW: 150,
    laborRate: 15,
    packagingCost: 0.5,
    targetMargin: 0.4,
    wholesaleMargin: 0.25,
    retailMargin: 0.479,
  },
  products: [
    { id: "p1", name: "Coasters", unitsPerPlate: 8, printHrsPerPlate: 9, filamentGPerPlate: 114, postProcessMinPerUnit: 5, setupMonitorMinPerPlate: 30, materialId: "m1" },
    { id: "p2", name: "Croc Charms", unitsPerPlate: 30, printHrsPerPlate: 1, filamentGPerPlate: 90, postProcessMinPerUnit: 2, setupMonitorMinPerPlate: 15, materialId: "m1" },
  ],
  clients: [
    { id: "c1", name: "Total Avantgarde Sdn Bhd", contact: "", email: "", phone: "", notes: "Helicopter / helideck display model" },
  ],
  materials: [
    { id: "m1", name: "PLA Generic", costPerKg: 50, stockGrams: 0, reorderThresholdGrams: 500, supplier: "", notes: "" },
  ],
  orders: [],
  transactions: [],
  counters: {},
});

const n = (v) => (isNaN(parseFloat(v)) ? 0 : parseFloat(v));
const rm = (v) => `RM ${(isNaN(v) ? 0 : v).toFixed(2)}`;
const uid = () => Math.random().toString(36).slice(2, 10);

function calcProduct(p, a) {
  const unitsPerPlate = n(p.unitsPerPlate);
  if (unitsPerPlate <= 0) return null;
  const printHrsPerPlate = n(p.printHrsPerPlate);
  const filamentGPerPlate = n(p.filamentGPerPlate);
  const postProcessMinPerUnit = n(p.postProcessMinPerUnit);
  const setupMonitorMinPerPlate = n(p.setupMonitorMinPerPlate);

  const filamentGPerUnit = filamentGPerPlate / unitsPerPlate;
  const printHrPerUnit = printHrsPerPlate / unitsPerPlate;
  const filamentCost = (filamentGPerUnit / 1000) * n(a.filamentCostPerKg);
  const electricityCost = ((printHrsPerPlate * n(a.printerPowerW)) / 1000) * n(a.electricityRate) / unitsPerPlate;
  const depreciationCost = ((n(a.printerPrice) / n(a.printerLifetimeHrs)) * printHrsPerPlate) / unitsPerPlate;
  const laborCost = (setupMonitorMinPerPlate / 60) * n(a.laborRate) / unitsPerPlate + (postProcessMinPerUnit / 60) * n(a.laborRate);
  const packagingCost = n(a.packagingCost);
  const totalCost = filamentCost + electricityCost + depreciationCost + laborCost + packagingCost;
  const suggestedPrice = totalCost / (1 - n(a.targetMargin));
  const margin = suggestedPrice - totalCost;
  const wholesalePrice = totalCost / (1 - n(a.wholesaleMargin));
  const wholesaleMarginRM = wholesalePrice - totalCost;
  const shopRetailPrice = wholesalePrice / (1 - n(a.retailMargin));

  return {
    filamentGPerUnit, printHrPerUnit, filamentCost, electricityCost, depreciationCost,
    laborCost, packagingCost, totalCost, suggestedPrice, margin, wholesalePrice,
    wholesaleMarginRM, shopRetailPrice,
  };
}

function nextDocNumber(core, type) {
  const year = new Date().getFullYear();
  const key = `${DOC_PREFIX[type]}-${year}`;
  const next = (core.counters[key] || 0) + 1;
  core.counters[key] = next;
  return `${DOC_PREFIX[type]}-${year}-${String(next).padStart(3, "0")}`;
}
function nextOrderNumber(core) {
  const year = new Date().getFullYear();
  const key = `ORD-${year}`;
  const next = (core.counters[key] || 0) + 1;
  core.counters[key] = next;
  return `ORD-${year}-${String(next).padStart(3, "0")}`;
}

function orderTotal(order) {
  return (order.items || []).reduce((s, it) => s + n(it.qty) * n(it.unitPrice), 0);
}
function orderCOGS(order) {
  return (order.items || []).reduce((s, it) => s + n(it.qty) * n(it.unitCost), 0);
}
function monthKey(dateStr) {
  return (dateStr || "").slice(0, 7) || "unknown";
}
function financeSummary(transactions) {
  const revenue = transactions.filter((t) => t.type === "income").reduce((s, t) => s + n(t.amount), 0);
  const cogs = transactions.filter((t) => t.autoGenerated).reduce((s, t) => s + n(t.cogs), 0);
  const expenses = transactions.filter((t) => t.type === "expense").reduce((s, t) => s + n(t.amount), 0);
  const grossProfit = revenue - cogs;
  const netProfit = grossProfit - expenses;
  return { revenue, cogs, expenses, grossProfit, netProfit };
}
function lowStockMaterials(materials) {
  return (materials || []).filter((m) => n(m.stockGrams) < n(m.reorderThresholdGrams));
}

// ---------- main component ----------
export default function OrdoAdmin() {
  const [core, setCore] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saveError, setSaveError] = useState("");
  const [currentUser, setCurrentUser] = useState(null);
  const [loginPick, setLoginPick] = useState(null);
  const [pinInput, setPinInput] = useState("");
  const [loginError, setLoginError] = useState("");
  const [tab, setTab] = useState("dashboard");
  const [selectedOrderId, setSelectedOrderId] = useState(null);
  const [showNewOrder, setShowNewOrder] = useState(false);
  const [previewDoc, setPreviewDoc] = useState(null); // {order, doc}

  useEffect(() => {
    (async () => {
      try {
        const res = await fetch("/admin/manage-data").then((r) => r.json());
        setCore(res && res.value ? JSON.parse(res.value) : defaultCore());
      } catch (e) {
        setCore(defaultCore());
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const persist = useCallback(async (newCore) => {
    setCore(newCore);
    try {
      const res = await fetch("/admin/manage-data", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newCore),
      });
      if (!res.ok) setSaveError("Save may not have gone through — check connection.");
      else setSaveError("");
    } catch (e) {
      setSaveError("Could not save to shared storage. Your change is visible to you but may not sync.");
    }
  }, []);

  if (loading || !core) {
    return (
      <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: 400, fontFamily: "Inter, sans-serif", color: "#8A8F98" }}>
        Loading Ordo Admin…
      </div>
    );
  }

  if (!currentUser) {
    return (
      <LoginScreen
        core={core}
        loginPick={loginPick}
        setLoginPick={setLoginPick}
        pinInput={pinInput}
        setPinInput={setPinInput}
        loginError={loginError}
        setLoginError={setLoginError}
        onSuccess={(u) => {
          setCurrentUser(u);
          setLoginPick(null);
          setPinInput("");
          setLoginError("");
        }}
      />
    );
  }

  const selectedOrder = core.orders.find((o) => o.id === selectedOrderId) || null;

  return (
    <div className="ordo-app">
      <style>{CSS}</style>
      <Sidebar tab={tab} setTab={(t) => { setTab(t); setSelectedOrderId(null); }} currentUser={currentUser} onLogout={() => setCurrentUser(null)} />
      <main className="ordo-main">
        {saveError && <div className="ordo-banner">{saveError}</div>}
        {tab === "dashboard" && <Dashboard core={core} onOpenOrder={(id) => { setTab("orders"); setSelectedOrderId(id); }} />}
        {tab === "orders" && !selectedOrder && (
          <OrdersBoard
            core={core}
            onSelect={setSelectedOrderId}
            onNew={() => setShowNewOrder(true)}
          />
        )}
        {tab === "orders" && selectedOrder && (
          <OrderDetail
            core={core}
            order={selectedOrder}
            currentUser={currentUser}
            onBack={() => setSelectedOrderId(null)}
            onUpdate={(updatedOrder) => {
              const newCore = { ...core, orders: core.orders.map((o) => (o.id === updatedOrder.id ? updatedOrder : o)) };
              const prevOrder = core.orders.find((o) => o.id === updatedOrder.id);

              if (prevOrder && prevOrder.status !== "In Production" && updatedOrder.status === "In Production" && !updatedOrder.materialsDeducted) {
                const deductions = [];
                const materials = (newCore.materials || []).map((m) => ({ ...m }));
                updatedOrder.items.filter((it) => it.kind === "product").forEach((it) => {
                  const product = newCore.products.find((p) => p.id === it.productId);
                  if (!product || !product.materialId) return;
                  const material = materials.find((m) => m.id === product.materialId);
                  if (!material) return;
                  const calc = calcProduct(product, newCore.assumptions);
                  if (!calc) return;
                  const gramsUsed = calc.filamentGPerUnit * n(it.qty);
                  material.stockGrams = n(material.stockGrams) - gramsUsed;
                  deductions.push({ materialId: material.id, materialName: material.name, gramsUsed: Number(gramsUsed.toFixed(1)) });
                });
                newCore.materials = materials;
                const idx = newCore.orders.findIndex((o) => o.id === updatedOrder.id);
                newCore.orders[idx] = { ...updatedOrder, materialsDeducted: true, materialDeductions: deductions };
              } else {
                const idx = newCore.orders.findIndex((o) => o.id === updatedOrder.id);
                newCore.orders[idx] = updatedOrder;
              }

              if (prevOrder && prevOrder.status !== "Paid" && updatedOrder.status === "Paid") {
                const alreadyLogged = (newCore.transactions || []).some((t) => t.orderId === updatedOrder.id && t.autoGenerated);
                if (!alreadyLogged) {
                  newCore.transactions = [
                    ...(newCore.transactions || []),
                    {
                      id: uid(),
                      date: new Date().toISOString().slice(0, 10),
                      type: "income",
                      category: "Sales",
                      description: `Order ${updatedOrder.orderNumber} — ${updatedOrder.clientName}`,
                      amount: orderTotal(updatedOrder),
                      cogs: orderCOGS(updatedOrder),
                      orderId: updatedOrder.id,
                      autoGenerated: true,
                      createdBy: currentUser.name,
                    },
                  ];
                }
              }
              persist(newCore);
            }}
            onGenerateDoc={(type) => {
              const newCore = JSON.parse(JSON.stringify(core));
              const docNumber = nextDocNumber(newCore, type);
              const ord = newCore.orders.find((o) => o.id === selectedOrder.id);
              const subtotal = orderTotal(ord);
              const doc = {
                id: uid(),
                type,
                docNumber,
                date: new Date().toISOString().slice(0, 10),
                items: ord.items.map((it) => ({ ...it })),
                subtotal,
                taxRate: 0,
                total: subtotal,
              };
              ord.documents = ord.documents || [];
              ord.documents.push(doc);
              persist(newCore);
            }}
            onPreviewDoc={(doc) => setPreviewDoc({ order: selectedOrder, doc })}
            onDeleteDoc={(docId) => {
              const newCore = { ...core, orders: core.orders.map((o) => (o.id === selectedOrder.id ? { ...o, documents: (o.documents || []).filter((d) => d.id !== docId) } : o)) };
              persist(newCore);
            }}
          />
        )}
        {tab === "finance" && (
          <Finance
            core={core}
            currentUser={currentUser}
            onAddTransaction={(t) => persist({ ...core, transactions: [...(core.transactions || []), t] })}
            onDeleteTransaction={(id) => persist({ ...core, transactions: (core.transactions || []).filter((t) => t.id !== id) })}
            onOpenOrder={(id) => { setTab("orders"); setSelectedOrderId(id); }}
          />
        )}
        {tab === "inventory" && (
          <Inventory core={core} onSave={(materials) => persist({ ...core, materials })} />
        )}
        {tab === "pricing" && (
          <PricingCalculator
            core={core}
            onSave={(assumptions, products) => persist({ ...core, assumptions, products })}
          />
        )}
        {tab === "clients" && (
          <Clients core={core} onSave={(clients) => persist({ ...core, clients })} />
        )}
        {tab === "settings" && (
          <Settings core={core} currentUser={currentUser} onSave={(companyInfo, users) => persist({ ...core, companyInfo, users })} />
        )}
      </main>
      {showNewOrder && (
        <NewOrderModal
          core={core}
          currentUser={currentUser}
          onClose={() => setShowNewOrder(false)}
          onCreate={(order) => {
            const newCore = JSON.parse(JSON.stringify(core));
            order.orderNumber = nextOrderNumber(newCore);
            newCore.orders.push(order);
            persist(newCore);
            setShowNewOrder(false);
            setTab("orders");
            setSelectedOrderId(order.id);
          }}
        />
      )}
      {previewDoc && (
        <DocPreview core={core} order={previewDoc.order} doc={previewDoc.doc} onClose={() => setPreviewDoc(null)} />
      )}
    </div>
  );
}

// ---------- login ----------
function LoginScreen({ core, loginPick, setLoginPick, pinInput, setPinInput, loginError, setLoginError, onSuccess }) {
  const submit = (pin) => {
    const user = core.users.find((u) => u.name === loginPick);
    if (user && user.pin === pin) {
      onSuccess(user);
    } else {
      setLoginError("Incorrect PIN");
      setPinInput("");
    }
  };
  const press = (d) => {
    if (pinInput.length >= 4) return;
    const next = pinInput + d;
    setPinInput(next);
    setLoginError("");
    if (next.length === 4) submit(next);
  };
  return (
    <div className="ordo-login">
      <style>{CSS}</style>
      <div className="ordo-login-card">
        <div className="ordo-brand">
          <span className="ordo-brand-mark">◆</span> ORDO
        </div>
        <div className="ordo-brand-sub">Admin System</div>
        {!loginPick ? (
          <>
            <div className="ordo-login-prompt">Who's working today?</div>
            <div className="ordo-user-grid">
              {core.users.map((u) => (
                <button key={u.name} className="ordo-user-btn" onClick={() => setLoginPick(u.name)}>
                  <span className="ordo-user-initial">{u.name[0]}</span>
                  <span className="ordo-user-name">{u.name}</span>
                </button>
              ))}
            </div>
          </>
        ) : (
          <>
            <div className="ordo-login-prompt">Enter PIN for {loginPick}</div>
            <div className="ordo-pin-dots">
              {[0, 1, 2, 3].map((i) => (
                <span key={i} className={"ordo-pin-dot" + (i < pinInput.length ? " filled" : "")} />
              ))}
            </div>
            {loginError && <div className="ordo-login-error">{loginError}</div>}
            <div className="ordo-keypad">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((d) => (
                <button key={d} className="ordo-key" onClick={() => press(String(d))}>{d}</button>
              ))}
              <button className="ordo-key ordo-key-ghost" onClick={() => { setLoginPick(null); setPinInput(""); setLoginError(""); }}>back</button>
              <button className="ordo-key" onClick={() => press("0")}>0</button>
              <button className="ordo-key ordo-key-ghost" onClick={() => setPinInput(pinInput.slice(0, -1))}>⌫</button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ---------- sidebar ----------
function Sidebar({ tab, setTab, currentUser, onLogout }) {
  const items = [
    { id: "dashboard", label: "Dashboard" },
    { id: "orders", label: "Orders" },
    { id: "finance", label: "Finance & PnL" },
    { id: "inventory", label: "Inventory" },
    { id: "pricing", label: "Pricing Calculator" },
    { id: "clients", label: "Clients" },
    { id: "settings", label: "Settings" },
  ];
  return (
    <nav className="ordo-sidebar">
      <div className="ordo-brand small">
        <span className="ordo-brand-mark">◆</span> ORDO
      </div>
      <div className="ordo-nav">
        {items.map((it) => (
          <button key={it.id} className={"ordo-nav-btn" + (tab === it.id ? " active" : "")} onClick={() => setTab(it.id)}>
            {it.label}
          </button>
        ))}
        <div className="ordo-nav-sep">Other dashboards</div>
        <a className="ordo-nav-link" href="/admin">Customer orders</a>
        <a className="ordo-nav-link" href="/admin/pilots">Pilot leads · Durible</a>
      </div>
      <div className="ordo-sidebar-footer">
        <div className="ordo-current-user">
          <span className="ordo-user-initial small">{currentUser.name[0]}</span>
          <div>
            <div className="ordo-cu-name">{currentUser.name}</div>
          </div>
        </div>
        <button className="ordo-logout" onClick={onLogout}>Log out</button>
      </div>
    </nav>
  );
}

// ---------- dashboard ----------
function Dashboard({ core, onOpenOrder }) {
  const counts = {};
  STATUS_FLOW.concat(["Cancelled"]).forEach((s) => (counts[s] = 0));
  core.orders.forEach((o) => (counts[o.status] = (counts[o.status] || 0) + 1));

  const pendingValue = core.orders
    .filter((o) => ["Lead", "Quotation Sent", "PO Confirmed", "In Production"].includes(o.status))
    .reduce((s, o) => s + orderTotal(o), 0);

  const paidValue = core.orders.filter((o) => o.status === "Paid").reduce((s, o) => s + orderTotal(o), 0);
  const fin = financeSummary(core.transactions || []);
  const low = lowStockMaterials(core.materials);

  const thisMonth = new Date().toISOString().slice(0, 7);
  const ordersThisMonth = core.orders.filter((o) => (o.createdDate || "").slice(0, 7) === thisMonth).length;
  const paidOrders = core.orders.filter((o) => o.status === "Paid");
  const avgOrderValue = paidOrders.length ? paidOrders.reduce((s, o) => s + orderTotal(o), 0) / paidOrders.length : 0;

  const recent = [...core.orders].sort((a, b) => (b.createdDate || "").localeCompare(a.createdDate || "")).slice(0, 6);

  return (
    <div className="ordo-page">
      <h1>Dashboard</h1>
      {low.length > 0 && (
        <div className="ordo-banner">Low stock: {low.map((m) => m.name).join(", ")} — check Inventory.</div>
      )}
      <div className="ordo-stat-row">
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Active orders</div>
          <div className="ordo-stat-value">{core.orders.filter((o) => o.status !== "Paid" && o.status !== "Cancelled").length}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Pipeline value (open)</div>
          <div className="ordo-stat-value mono">{rm(pendingValue)}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Paid to date</div>
          <div className="ordo-stat-value mono">{rm(paidValue)}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Clients</div>
          <div className="ordo-stat-value">{core.clients.length}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Net profit (all time)</div>
          <div className="ordo-stat-value mono">{rm(fin.netProfit)}</div>
        </div>
      </div>

      <div className="ordo-stat-row" style={{ gridTemplateColumns: "repeat(2,1fr)", marginTop: 14 }}>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">New orders this month</div>
          <div className="ordo-stat-value">{ordersThisMonth}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Average paid order value</div>
          <div className="ordo-stat-value mono">{rm(avgOrderValue)}</div>
        </div>
      </div>

      <div className="ordo-section-title">Pipeline by status</div>
      <div className="ordo-pipeline-bar">
        {STATUS_FLOW.map((s) => (
          <div key={s} className="ordo-pipeline-seg">
            <div className="ordo-pipeline-dot" style={{ background: STATUS_COLORS[s] }} />
            <div className="ordo-pipeline-label">{s}</div>
            <div className="ordo-pipeline-count">{counts[s]}</div>
          </div>
        ))}
      </div>

      <div className="ordo-section-title">Recent orders</div>
      <table className="ordo-table">
        <thead><tr><th>Order #</th><th>Client</th><th>Status</th><th>Value</th></tr></thead>
        <tbody>
          {recent.length === 0 && <tr><td colSpan={4} className="ordo-empty">No orders yet — create one from the Orders tab.</td></tr>}
          {recent.map((o) => (
            <tr key={o.id} className="ordo-clickable-row" onClick={() => onOpenOrder(o.id)}>
              <td className="mono">{o.orderNumber}</td>
              <td>{o.clientName}</td>
              <td><span className="ordo-status-pill" style={{ background: STATUS_COLORS[o.status] }}>{o.status}</span></td>
              <td className="mono">{rm(orderTotal(o))}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ---------- orders board ----------
function OrdersBoard({ core, onSelect, onNew }) {
  return (
    <div className="ordo-page">
      <div className="ordo-page-head">
        <h1>Orders</h1>
        <button className="ordo-btn-primary" onClick={onNew}>+ New order</button>
      </div>
      <div className="ordo-board">
        {STATUS_FLOW.map((status) => (
          <div key={status} className="ordo-board-col">
            <div className="ordo-board-col-head">
              <span className="ordo-pipeline-dot" style={{ background: STATUS_COLORS[status] }} />
              {status}
              <span className="ordo-board-count">{core.orders.filter((o) => o.status === status).length}</span>
            </div>
            <div className="ordo-board-cards">
              {core.orders.filter((o) => o.status === status).map((o) => (
                <div key={o.id} className="ordo-card" onClick={() => onSelect(o.id)}>
                  <div className="ordo-card-num mono">{o.orderNumber}</div>
                  <div className="ordo-card-client">{o.clientName}</div>
                  <div className="ordo-card-value mono">{rm(orderTotal(o))}</div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ---------- new order modal ----------
function NewOrderModal({ core, currentUser, onClose, onCreate }) {
  const [clientMode, setClientMode] = useState("existing");
  const [clientId, setClientId] = useState(core.clients[0]?.id || "");
  const [newClientName, setNewClientName] = useState("");
  const [title, setTitle] = useState("");
  const [notes, setNotes] = useState("");
  const [items, setItems] = useState([]);

  const addProductItem = () => {
    const p = core.products[0];
    if (!p) return;
    const calc = calcProduct(p, core.assumptions);
    setItems([...items, { id: uid(), kind: "product", productId: p.id, description: p.name, qty: 1, unitPrice: 0, unitCost: calc ? Number(calc.totalCost.toFixed(2)) : 0 }]);
  };
  const addCustomItem = () => setItems([...items, { id: uid(), kind: "custom", description: "", qty: 1, unitPrice: 0, unitCost: 0 }]);
  const updateItem = (id, patch) => setItems(items.map((it) => (it.id === id ? { ...it, ...patch } : it)));
  const removeItem = (id) => setItems(items.filter((it) => it.id !== id));

  const total = items.reduce((s, it) => s + n(it.qty) * n(it.unitPrice), 0);

  const clientName = clientMode === "existing" ? core.clients.find((c) => c.id === clientId)?.name || "" : newClientName;

  const canSave = clientName.trim() && items.length > 0;

  return (
    <div className="ordo-modal-overlay" onClick={onClose}>
      <div className="ordo-modal ordo-modal-wide" onClick={(e) => e.stopPropagation()}>
        <div className="ordo-modal-head">
          <h2>New order</h2>
          <button className="ordo-modal-close" onClick={onClose}>✕</button>
        </div>
        <div className="ordo-modal-body">
          <div className="ordo-form-row">
            <label>Client</label>
            <div className="ordo-toggle-group">
              <button className={clientMode === "existing" ? "active" : ""} onClick={() => setClientMode("existing")}>Existing</button>
              <button className={clientMode === "new" ? "active" : ""} onClick={() => setClientMode("new")}>New</button>
            </div>
          </div>
          {clientMode === "existing" ? (
            <select className="ordo-input" value={clientId} onChange={(e) => setClientId(e.target.value)}>
              {core.clients.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
            </select>
          ) : (
            <input className="ordo-input" placeholder="Client / company name" value={newClientName} onChange={(e) => setNewClientName(e.target.value)} />
          )}

          <div className="ordo-form-row" style={{ marginTop: 12 }}>
            <label>Order title (optional)</label>
          </div>
          <input className="ordo-input" placeholder="e.g. Helideck display model, batch 1" value={title} onChange={(e) => setTitle(e.target.value)} />

          <div className="ordo-section-title" style={{ marginTop: 16 }}>Line items</div>
          <table className="ordo-table ordo-table-compact">
            <thead><tr><th>Item</th><th style={{ width: 70 }}>Qty</th><th style={{ width: 110 }}>Unit price</th><th style={{ width: 100 }}>Unit cost</th><th style={{ width: 100 }}>Line total</th><th></th></tr></thead>
            <tbody>
              {items.map((it) => (
                <tr key={it.id}>
                  <td>
                    {it.kind === "product" ? (
                      <select className="ordo-input" value={it.productId} onChange={(e) => {
                        const p = core.products.find((pp) => pp.id === e.target.value);
                        const calc = p ? calcProduct(p, core.assumptions) : null;
                        updateItem(it.id, { productId: p.id, description: p.name, unitCost: calc ? Number(calc.totalCost.toFixed(2)) : it.unitCost });
                      }}>
                        {core.products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
                      </select>
                    ) : (
                      <input className="ordo-input" placeholder="Custom item description" value={it.description} onChange={(e) => updateItem(it.id, { description: e.target.value })} />
                    )}
                  </td>
                  <td><input className="ordo-input" type="number" min="1" value={it.qty} onChange={(e) => updateItem(it.id, { qty: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" step="0.01" value={it.unitPrice} onChange={(e) => updateItem(it.id, { unitPrice: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" step="0.01" value={it.unitCost} onChange={(e) => updateItem(it.id, { unitCost: e.target.value })} /></td>
                  <td className="mono">{rm(n(it.qty) * n(it.unitPrice))}</td>
                  <td><button className="ordo-icon-btn" onClick={() => removeItem(it.id)}>✕</button></td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="ordo-add-item-row">
            <button className="ordo-btn-ghost" onClick={addProductItem}>+ Product from calculator</button>
            <button className="ordo-btn-ghost" onClick={addCustomItem}>+ Custom line item</button>
          </div>
          <div className="ordo-hint">Unit price is your quoted price — enter it manually. Unit cost is pulled from the pricing calculator automatically for calculator products (fill it in for custom items) so Finance can still track margin correctly.</div>
          <div className="ordo-order-total">Total: <span className="mono">{rm(total)}</span></div>

          <div className="ordo-form-row" style={{ marginTop: 12 }}><label>Notes</label></div>
          <textarea className="ordo-input" rows={2} value={notes} onChange={(e) => setNotes(e.target.value)} />
        </div>
        <div className="ordo-modal-foot">
          <button className="ordo-btn-ghost" onClick={onClose}>Cancel</button>
          <button
            className="ordo-btn-primary"
            disabled={!canSave}
            onClick={() => {
              let cid = clientId;
              if (clientMode === "new") {
                cid = uid();
              }
              onCreate({
                id: uid(),
                clientId: cid,
                clientName,
                title,
                notes,
                items,
                status: "Lead",
                createdDate: new Date().toISOString().slice(0, 10),
                createdBy: currentUser.name,
                documents: [],
              });
            }}
          >Create order</button>
        </div>
      </div>
    </div>
  );
}

// ---------- order detail ----------
function OrderDetail({ core, order, currentUser, onBack, onUpdate, onGenerateDoc, onPreviewDoc, onDeleteDoc }) {
  const [notes, setNotes] = useState(order.notes || "");
  const [confirmingDocId, setConfirmingDocId] = useState(null);
  const total = orderTotal(order);

  return (
    <div className="ordo-page">
      <button className="ordo-back-btn" onClick={onBack}>← Back to orders</button>
      <div className="ordo-page-head">
        <div>
          <h1 className="mono">{order.orderNumber}</h1>
          <div className="ordo-sub">{order.clientName}{order.title ? ` — ${order.title}` : ""}</div>
        </div>
        <span className="ordo-status-pill large" style={{ background: STATUS_COLORS[order.status] }}>{order.status}</span>
      </div>

      <div className="ordo-section-title">Status</div>
      <div className="ordo-status-stepper">
        {STATUS_FLOW.map((s) => (
          <button
            key={s}
            className={"ordo-step" + (order.status === s ? " active" : "") + (STATUS_FLOW.indexOf(order.status) > STATUS_FLOW.indexOf(s) ? " done" : "")}
            onClick={() => onUpdate({ ...order, status: s })}
          >{s}</button>
        ))}
        <button className="ordo-step cancel" onClick={() => onUpdate({ ...order, status: "Cancelled" })}>Cancel order</button>
      </div>

      <div className="ordo-section-title">Line items</div>
      <table className="ordo-table">
        <thead><tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Unit cost</th><th>Line total</th><th>Margin</th></tr></thead>
        <tbody>
          {order.items.map((it) => (
            <tr key={it.id}>
              <td>{it.description}</td>
              <td className="mono">{it.qty}</td>
              <td className="mono">{rm(n(it.unitPrice))}</td>
              <td className="mono">{rm(n(it.unitCost))}</td>
              <td className="mono">{rm(n(it.qty) * n(it.unitPrice))}</td>
              <td className="mono">{rm(n(it.qty) * (n(it.unitPrice) - n(it.unitCost)))}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="ordo-order-total">Total: <span className="mono">{rm(total)}</span></div>
      <div className="ordo-order-total" style={{ color: "var(--muted)", fontSize: 12.5 }}>Estimated COGS: <span className="mono">{rm(orderCOGS(order))}</span> &nbsp;·&nbsp; Estimated margin: <span className="mono">{rm(total - orderCOGS(order))}</span></div>

      {order.materialDeductions && order.materialDeductions.length > 0 && (
        <div className="ordo-hint">
          Materials deducted on entering production: {order.materialDeductions.map((d) => `${d.materialName} −${d.gramsUsed}g`).join(", ")}
        </div>
      )}

      <div className="ordo-section-title">Documents</div>
      <div className="ordo-doc-actions">
        {Object.keys(DOC_PREFIX).map((type) => (
          <button key={type} className="ordo-btn-ghost" onClick={() => onGenerateDoc(type)}>Generate {type}</button>
        ))}
      </div>
      <table className="ordo-table ordo-table-compact">
        <thead><tr><th>Doc #</th><th>Type</th><th>Date</th><th>Total</th><th></th><th></th></tr></thead>
        <tbody>
          {(order.documents || []).length === 0 && <tr><td colSpan={6} className="ordo-empty">No documents generated yet.</td></tr>}
          {(order.documents || []).map((d) => (
            <tr key={d.id}>
              <td className="mono">{d.docNumber}</td>
              <td>{d.type}</td>
              <td>{d.date}</td>
              <td className="mono">{rm(d.total)}</td>
              <td><button className="ordo-btn-ghost small" onClick={() => onPreviewDoc(d)}>View</button></td>
              <td>
                {confirmingDocId === d.id ? (
                  <div style={{ display: "flex", gap: 6 }}>
                    <button className="ordo-btn-ghost small" onClick={() => { onDeleteDoc(d.id); setConfirmingDocId(null); }}>Confirm delete</button>
                    <button className="ordo-btn-ghost small" onClick={() => setConfirmingDocId(null)}>Cancel</button>
                  </div>
                ) : (
                  <button className="ordo-icon-btn" onClick={() => setConfirmingDocId(d.id)}>✕</button>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="ordo-section-title">Notes</div>
      <textarea className="ordo-input" rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} onBlur={() => onUpdate({ ...order, notes })} />
    </div>
  );
}

// ---------- document preview ----------
function DocPreview({ core, order, doc, onClose }) {
  const ci = core.companyInfo;
  return (
    <div className="ordo-modal-overlay" onClick={onClose}>
      <div className="ordo-modal ordo-doc-modal" onClick={(e) => e.stopPropagation()}>
        <div className="ordo-modal-head no-print">
          <h2>{doc.type} {doc.docNumber}</h2>
          <div>
            <button className="ordo-btn-ghost" onClick={() => window.print()}>Print</button>
            <button className="ordo-modal-close" onClick={onClose}>✕</button>
          </div>
        </div>
        <div className="ordo-doc-paper">
          <div className="ordo-doc-header">
            <div>
              <div className="ordo-doc-company">{ci.name}</div>
              <div className="ordo-doc-tagline">{ci.tagline}</div>
              {ci.address && ci.address.split("\n").map((line, i) => <div key={i} className="ordo-doc-line">{line}</div>)}
              {ci.phone && <div className="ordo-doc-line">{ci.phone}</div>}
              {ci.email && <div className="ordo-doc-line">{ci.email}</div>}
            </div>
            <div className="ordo-doc-meta">
              <div className="ordo-doc-type">{doc.type.toUpperCase()}</div>
              <div className="mono">{doc.docNumber}</div>
              <div>{doc.date}</div>
            </div>
          </div>
          <div className="ordo-doc-bill">
            <div className="ordo-doc-label">Bill to</div>
            <div>{order.clientName}</div>
            {(() => {
              const client = core.clients.find((c) => c.id === order.clientId);
              return client && client.address ? client.address.split("\n").map((line, i) => <div key={i} className="ordo-doc-line">{line}</div>) : null;
            })()}
          </div>
          <table className="ordo-doc-table">
            <thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead>
            <tbody>
              {doc.items.map((it) => (
                <tr key={it.id}>
                  <td>{it.description}</td>
                  <td className="mono">{it.qty}</td>
                  <td className="mono">{rm(n(it.unitPrice))}</td>
                  <td className="mono">{rm(n(it.qty) * n(it.unitPrice))}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="ordo-doc-totals">
            <div>Subtotal <span className="mono">{rm(doc.subtotal)}</span></div>
            <div className="grand">Total <span className="mono">{rm(doc.total)}</span></div>
          </div>
          {ci.bankDetails && doc.type !== "Quotation" && (
            <div className="ordo-doc-bank"><div className="ordo-doc-label">Payment details</div><div>{ci.bankDetails}</div></div>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------- finance & pnl ----------
const EXPENSE_CATEGORIES = ["Materials", "Equipment", "Labor", "Marketing", "Rent & Utilities", "Other"];
const INCOME_CATEGORIES = ["Sales", "Other Income"];

function Finance({ core, currentUser, onAddTransaction, onDeleteTransaction, onOpenOrder }) {
  const transactions = core.transactions || [];
  const [form, setForm] = useState({ type: "expense", category: "Materials", description: "", amount: "", date: new Date().toISOString().slice(0, 10) });

  const summary = financeSummary(transactions);

  const months = Array.from(new Set(transactions.map((t) => monthKey(t.date)))).sort().reverse();
  const monthRows = months.map((m) => {
    const tx = transactions.filter((t) => monthKey(t.date) === m);
    const s = financeSummary(tx);
    return { month: m, ...s };
  });

  const sorted = [...transactions].sort((a, b) => (b.date || "").localeCompare(a.date || ""));

  return (
    <div className="ordo-page">
      <h1>Finance &amp; PnL</h1>

      <div className="ordo-stat-row" style={{ gridTemplateColumns: "repeat(4,1fr)" }}>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Revenue (all time)</div>
          <div className="ordo-stat-value mono">{rm(summary.revenue)}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Est. COGS (from pricing)</div>
          <div className="ordo-stat-value mono">{rm(summary.cogs)}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Other expenses</div>
          <div className="ordo-stat-value mono">{rm(summary.expenses)}</div>
        </div>
        <div className="ordo-stat-card">
          <div className="ordo-stat-label">Net profit</div>
          <div className="ordo-stat-value mono">{rm(summary.netProfit)}</div>
        </div>
      </div>
      <div className="ordo-hint">
        Revenue and COGS post automatically when an order's status is set to "Paid" — COGS comes straight from the pricing calculator's cost breakdown at the time of sale.
        Use the ledger below only for everything else: bulk material purchases, equipment, labor payments, rent, marketing, and any other income.
        If you log a bulk material purchase here as an expense, avoid also letting per-unit COGS double-count that same material — pick one method and stay consistent.
      </div>

      <div className="ordo-section-title">Monthly PnL</div>
      <table className="ordo-table ordo-table-compact">
        <thead><tr><th>Month</th><th>Revenue</th><th>COGS</th><th>Gross profit</th><th>Other expenses</th><th>Net profit</th></tr></thead>
        <tbody>
          {monthRows.length === 0 && <tr><td colSpan={6} className="ordo-empty">No transactions yet.</td></tr>}
          {monthRows.map((r) => (
            <tr key={r.month}>
              <td className="mono">{r.month}</td>
              <td className="mono">{rm(r.revenue)}</td>
              <td className="mono">{rm(r.cogs)}</td>
              <td className="mono">{rm(r.grossProfit)}</td>
              <td className="mono">{rm(r.expenses)}</td>
              <td className="mono">{rm(r.netProfit)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="ordo-section-title">Add a ledger entry</div>
      <div className="ordo-ledger-form">
        <div className="ordo-toggle-group">
          <button className={form.type === "expense" ? "active" : ""} onClick={() => setForm({ ...form, type: "expense", category: EXPENSE_CATEGORIES[0] })}>Expense</button>
          <button className={form.type === "income" ? "active" : ""} onClick={() => setForm({ ...form, type: "income", category: INCOME_CATEGORIES[0] })}>Income</button>
        </div>
        <select className="ordo-input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>
          {(form.type === "expense" ? EXPENSE_CATEGORIES : INCOME_CATEGORIES).map((c) => <option key={c} value={c}>{c}</option>)}
        </select>
        <input className="ordo-input" type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />
        <input className="ordo-input" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
        <input className="ordo-input" type="number" step="0.01" placeholder="Amount (RM)" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} />
        <button
          className="ordo-btn-primary"
          disabled={!form.description.trim() || !(n(form.amount) > 0)}
          onClick={() => {
            onAddTransaction({ id: uid(), ...form, amount: n(form.amount), autoGenerated: false, createdBy: currentUser.name });
            setForm({ type: form.type, category: form.category, description: "", amount: "", date: new Date().toISOString().slice(0, 10) });
          }}
        >Add entry</button>
      </div>

      <div className="ordo-section-title">Ledger</div>
      <table className="ordo-table ordo-table-compact">
        <thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Amount</th><th></th></tr></thead>
        <tbody>
          {sorted.length === 0 && <tr><td colSpan={6} className="ordo-empty">No entries yet.</td></tr>}
          {sorted.map((t) => (
            <tr key={t.id}>
              <td className="mono">{t.date}</td>
              <td>{t.type === "income" ? "Income" : "Expense"}</td>
              <td>{t.category}</td>
              <td>
                {t.orderId ? (
                  <button className="ordo-link-btn" onClick={() => onOpenOrder(t.orderId)}>{t.description}</button>
                ) : t.description}
              </td>
              <td className="mono">{rm(t.amount)}</td>
              <td>{!t.autoGenerated && <button className="ordo-icon-btn" onClick={() => onDeleteTransaction(t.id)}>✕</button>}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ---------- inventory ----------
function Inventory({ core, onSave }) {
  const [materials, setMaterials] = useState(core.materials || []);
  const [restockAmount, setRestockAmount] = useState({});

  const update = (id, patch) => setMaterials(materials.map((m) => (m.id === id ? { ...m, ...patch } : m)));
  const add = () => setMaterials([...materials, { id: uid(), name: "New material", costPerKg: 50, stockGrams: 0, reorderThresholdGrams: 500, supplier: "", notes: "" }]);
  const remove = (id) => setMaterials(materials.filter((m) => m.id !== id));
  const restock = (id) => {
    const amt = n(restockAmount[id]);
    if (amt <= 0) return;
    update(id, { stockGrams: n(materials.find((m) => m.id === id).stockGrams) + amt });
    setRestockAmount({ ...restockAmount, [id]: "" });
  };

  const low = lowStockMaterials(materials);

  return (
    <div className="ordo-page">
      <div className="ordo-page-head">
        <h1>Inventory</h1>
        <button className="ordo-btn-primary" onClick={() => onSave(materials)}>Save changes</button>
      </div>

      {low.length > 0 && (
        <div className="ordo-banner">Low stock: {low.map((m) => m.name).join(", ")} — below reorder threshold.</div>
      )}

      <div className="ordo-hint">
        Link materials to products in the Pricing Calculator's "Material" column so stock deducts automatically when an order enters "In Production."
      </div>

      <table className="ordo-table ordo-table-compact" style={{ marginTop: 14 }}>
        <thead><tr><th>Material</th><th>Cost/kg (RM)</th><th>Stock (g)</th><th>Reorder at (g)</th><th>Supplier</th><th>Restock</th><th></th></tr></thead>
        <tbody>
          {materials.map((m) => {
            const isLow = n(m.stockGrams) < n(m.reorderThresholdGrams);
            return (
              <tr key={m.id} style={isLow ? { background: "#F0E2C4" } : undefined}>
                <td><input className="ordo-input" value={m.name} onChange={(e) => update(m.id, { name: e.target.value })} /></td>
                <td><input className="ordo-input" type="number" step="0.01" value={m.costPerKg} onChange={(e) => update(m.id, { costPerKg: e.target.value })} /></td>
                <td className="mono">{n(m.stockGrams).toFixed(0)}</td>
                <td><input className="ordo-input" type="number" value={m.reorderThresholdGrams} onChange={(e) => update(m.id, { reorderThresholdGrams: e.target.value })} /></td>
                <td><input className="ordo-input" value={m.supplier} onChange={(e) => update(m.id, { supplier: e.target.value })} /></td>
                <td>
                  <div style={{ display: "flex", gap: 6 }}>
                    <input className="ordo-input" type="number" placeholder="+g" style={{ width: 70 }} value={restockAmount[m.id] || ""} onChange={(e) => setRestockAmount({ ...restockAmount, [m.id]: e.target.value })} />
                    <button className="ordo-btn-ghost small" onClick={() => restock(m.id)}>Add</button>
                  </div>
                </td>
                <td><button className="ordo-icon-btn" onClick={() => remove(m.id)}>✕</button></td>
              </tr>
            );
          })}
        </tbody>
      </table>
      <button className="ordo-btn-ghost" style={{ marginTop: 10 }} onClick={add}>+ Add material</button>
    </div>
  );
}

// ---------- pricing calculator ----------
function PricingCalculator({ core, onSave }) {
  const [assumptions, setAssumptions] = useState(core.assumptions);
  const [products, setProducts] = useState(core.products);

  const fields = [
    ["filamentCostPerKg", "Filament cost (RM per kg)"],
    ["electricityRate", "Electricity rate (RM per kWh)"],
    ["printerPrice", "Printer purchase price (RM)"],
    ["printerLifetimeHrs", "Printer expected lifetime (hours)"],
    ["printerPowerW", "Printer average power draw (W)"],
    ["laborRate", "Labor rate (RM per hour)"],
    ["packagingCost", "Packaging cost per unit (RM)"],
    ["targetMargin", "Target margin (fraction, e.g. 0.4 = 40%)"],
    ["wholesaleMargin", "Wholesale margin (fraction)"],
    ["retailMargin", "Shop retail margin (fraction)"],
  ];

  const updateProduct = (id, patch) => setProducts(products.map((p) => (p.id === id ? { ...p, ...patch } : p)));
  const addProduct = () => setProducts([...products, { id: uid(), name: "New product", unitsPerPlate: 1, printHrsPerPlate: 1, filamentGPerPlate: 0, postProcessMinPerUnit: 0, setupMonitorMinPerPlate: 0 }]);
  const removeProduct = (id) => setProducts(products.filter((p) => p.id !== id));

  return (
    <div className="ordo-page">
      <div className="ordo-page-head">
        <h1>Pricing Calculator</h1>
        <button className="ordo-btn-primary" onClick={() => onSave(assumptions, products)}>Save changes</button>
      </div>

      <div className="ordo-section-title">Global assumptions</div>
      <div className="ordo-assumptions-grid">
        {fields.map(([key, label]) => (
          <div key={key} className="ordo-assumption">
            <label>{label}</label>
            <input className="ordo-input" type="number" step="0.001" value={assumptions[key]} onChange={(e) => setAssumptions({ ...assumptions, [key]: e.target.value })} />
          </div>
        ))}
      </div>

      <div className="ordo-section-title">Per-product pricing</div>
      <div className="ordo-table-scroll">
        <table className="ordo-table ordo-table-compact">
          <thead>
            <tr>
              <th>Product</th><th>Units/plate</th><th>Print hrs/plate</th><th>Filament g/plate</th>
              <th>Post-process min/unit</th><th>Setup+monitor min/plate</th><th>Material</th>
              <th>Cost/unit</th><th>Suggested price</th><th>Wholesale price</th><th>Shop retail</th><th></th>
            </tr>
          </thead>
          <tbody>
            {products.map((p) => {
              const calc = calcProduct(p, assumptions);
              return (
                <tr key={p.id}>
                  <td><input className="ordo-input" value={p.name} onChange={(e) => updateProduct(p.id, { name: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" value={p.unitsPerPlate} onChange={(e) => updateProduct(p.id, { unitsPerPlate: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" value={p.printHrsPerPlate} onChange={(e) => updateProduct(p.id, { printHrsPerPlate: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" value={p.filamentGPerPlate} onChange={(e) => updateProduct(p.id, { filamentGPerPlate: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" value={p.postProcessMinPerUnit} onChange={(e) => updateProduct(p.id, { postProcessMinPerUnit: e.target.value })} /></td>
                  <td><input className="ordo-input" type="number" value={p.setupMonitorMinPerPlate} onChange={(e) => updateProduct(p.id, { setupMonitorMinPerPlate: e.target.value })} /></td>
                  <td>
                    <select className="ordo-input" value={p.materialId || ""} onChange={(e) => updateProduct(p.id, { materialId: e.target.value || null })}>
                      <option value="">— none —</option>
                      {(core.materials || []).map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}
                    </select>
                  </td>
                  <td className="mono">{calc ? rm(calc.totalCost) : "—"}</td>
                  <td className="mono">{calc ? rm(calc.suggestedPrice) : "—"}</td>
                  <td className="mono">{calc ? rm(calc.wholesalePrice) : "—"}</td>
                  <td className="mono">{calc ? rm(calc.shopRetailPrice) : "—"}</td>
                  <td><button className="ordo-icon-btn" onClick={() => removeProduct(p.id)}>✕</button></td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <button className="ordo-btn-ghost" style={{ marginTop: 10 }} onClick={addProduct}>+ Add product</button>
    </div>
  );
}

// ---------- clients ----------
function Clients({ core, onSave }) {
  const [clients, setClients] = useState(core.clients);
  const update = (id, patch) => setClients(clients.map((c) => (c.id === id ? { ...c, ...patch } : c)));
  const add = () => setClients([...clients, { id: uid(), name: "New client", contact: "", email: "", phone: "", address: "", notes: "" }]);
  const remove = (id) => setClients(clients.filter((c) => c.id !== id));

  return (
    <div className="ordo-page">
      <div className="ordo-page-head">
        <h1>Clients</h1>
        <button className="ordo-btn-primary" onClick={() => onSave(clients)}>Save changes</button>
      </div>
      <div className="ordo-client-list">
        {clients.map((c) => (
          <div key={c.id} className="ordo-client-card">
            <input className="ordo-input ordo-client-name" value={c.name} onChange={(e) => update(c.id, { name: e.target.value })} />
            <div className="ordo-client-grid">
              <input className="ordo-input" placeholder="Contact person" value={c.contact} onChange={(e) => update(c.id, { contact: e.target.value })} />
              <input className="ordo-input" placeholder="Email" value={c.email} onChange={(e) => update(c.id, { email: e.target.value })} />
              <input className="ordo-input" placeholder="Phone" value={c.phone} onChange={(e) => update(c.id, { phone: e.target.value })} />
            </div>
            <textarea className="ordo-input" rows={2} placeholder="Address" value={c.address || ""} onChange={(e) => update(c.id, { address: e.target.value })} />
            <textarea className="ordo-input" rows={2} placeholder="Notes" value={c.notes} onChange={(e) => update(c.id, { notes: e.target.value })} />
            <button className="ordo-btn-ghost small" onClick={() => remove(c.id)}>Remove client</button>
          </div>
        ))}
      </div>
      <button className="ordo-btn-ghost" style={{ marginTop: 10 }} onClick={add}>+ Add client</button>
    </div>
  );
}

// ---------- settings ----------
function Settings({ core, currentUser, onSave }) {
  const [companyInfo, setCompanyInfo] = useState(core.companyInfo);
  const [users, setUsers] = useState(core.users);
  const [pinEdit, setPinEdit] = useState("");
  const [newName, setNewName] = useState("");

  const myUser = users.find((u) => u.name === currentUser.name);

  return (
    <div className="ordo-page">
      <div className="ordo-page-head">
        <h1>Settings</h1>
        <button className="ordo-btn-primary" onClick={() => onSave(companyInfo, users)}>Save changes</button>
      </div>

      <div className="ordo-section-title">Team members</div>
      <table className="ordo-table ordo-table-compact">
        <thead><tr><th>Name</th><th></th></tr></thead>
        <tbody>
          {users.map((u) => (
            <tr key={u.name}>
              <td>{u.name}{u.name === currentUser.name ? " (you)" : ""}</td>
              <td>
                {u.name !== currentUser.name && (
                  <button className="ordo-icon-btn" onClick={() => setUsers(users.filter((x) => x.name !== u.name))}>✕</button>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="ordo-pin-edit-row" style={{ marginTop: 10 }}>
        <input className="ordo-input" style={{ maxWidth: 220 }} placeholder="New team member's name" value={newName} onChange={(e) => setNewName(e.target.value)} />
        <button
          className="ordo-btn-ghost"
          disabled={!newName.trim() || users.some((u) => u.name.toLowerCase() === newName.trim().toLowerCase())}
          onClick={() => { setUsers([...users, { name: newName.trim(), pin: "1234" }]); setNewName(""); }}
        >Add person</button>
      </div>
      <div className="ordo-hint">New people start with PIN 1234 — they should set their own under "Your PIN" below once they log in. Remember to click "Save changes" above for this to apply.</div>

      <div className="ordo-section-title">Company info (used on quotations / invoices / receipts)</div>
      <div className="ordo-assumptions-grid">
        <div className="ordo-assumption"><label>Business name</label><input className="ordo-input" value={companyInfo.name} onChange={(e) => setCompanyInfo({ ...companyInfo, name: e.target.value })} /></div>
        <div className="ordo-assumption"><label>Tagline</label><input className="ordo-input" value={companyInfo.tagline} onChange={(e) => setCompanyInfo({ ...companyInfo, tagline: e.target.value })} /></div>
        <div className="ordo-assumption" style={{ gridColumn: "span 2" }}><label>Address</label><textarea className="ordo-input" rows={3} placeholder={"Unit / building\nStreet, area\nPostcode City, State"} value={companyInfo.address} onChange={(e) => setCompanyInfo({ ...companyInfo, address: e.target.value })} /></div>
        <div className="ordo-assumption"><label>Phone</label><input className="ordo-input" value={companyInfo.phone} onChange={(e) => setCompanyInfo({ ...companyInfo, phone: e.target.value })} /></div>
        <div className="ordo-assumption"><label>Email</label><input className="ordo-input" value={companyInfo.email} onChange={(e) => setCompanyInfo({ ...companyInfo, email: e.target.value })} /></div>
        <div className="ordo-assumption"><label>Bank details (for invoices/receipts)</label><input className="ordo-input" value={companyInfo.bankDetails} onChange={(e) => setCompanyInfo({ ...companyInfo, bankDetails: e.target.value })} /></div>
      </div>

      <div className="ordo-section-title">Your PIN</div>
      <div className="ordo-pin-edit-row">
        <input className="ordo-input" style={{ maxWidth: 160 }} type="text" maxLength={4} placeholder="New 4-digit PIN" value={pinEdit} onChange={(e) => setPinEdit(e.target.value.replace(/\D/g, "").slice(0, 4))} />
        <button
          className="ordo-btn-ghost"
          disabled={pinEdit.length !== 4}
          onClick={() => {
            setUsers(users.map((u) => (u.name === currentUser.name ? { ...u, pin: pinEdit } : u)));
            setPinEdit("");
          }}
        >Update my PIN</button>
      </div>
      <div className="ordo-hint">Everyone's PIN starts as 1234 by default — each person should set their own here. You can only change your own PIN.</div>
    </div>
  );
}


// ---------- styles ----------
const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

:root{
  --bg:#F5F3ED;
  --surface:#FFFFFF;
  --surface-2:#FAF8F3;
  --sidebar:#14150F;
  --sidebar-2:#1E2017;
  --line:#E4DFD2;
  --line-2:#D5CEBC;
  --gold:#C6A96A;
  --gold-dim:#A98D51;
  --sage:#7E9469;
  --text:#22241C;
  --muted:#6F6B5C;
  --muted-2:#9A9585;
  --danger:#C23B3B;
  --shadow-sm:0 1px 2px rgba(34,36,28,0.06);
  --shadow:0 2px 8px rgba(34,36,28,0.07);
  --shadow-lg:0 12px 32px rgba(34,36,28,0.14);
  --r:10px;
  --r-lg:14px;
}

.ordo-app *,.ordo-login *{ box-sizing:border-box; }
.ordo-app{ display:flex; min-height:100vh; font-family:'Inter',sans-serif; color:var(--text); background:var(--bg); -webkit-font-smoothing:antialiased; }
.mono{ font-family:'JetBrains Mono',monospace; font-variant-numeric:tabular-nums; }

/* ---------- login ---------- */
.ordo-login{ min-height:100vh; display:flex; align-items:center; justify-content:center; padding:24px;
  background:radial-gradient(ellipse at 50% -10%, #23261C 0%, #14150F 60%); font-family:'Inter',sans-serif; }
.ordo-login-card{ background:var(--surface); border-radius:20px; padding:40px 40px 34px; width:100%; max-width:420px;
  text-align:center; box-shadow:0 24px 60px rgba(0,0,0,0.45); }
.ordo-brand{ font-family:'Oswald',sans-serif; font-weight:600; letter-spacing:0.18em; font-size:24px; color:var(--text); }
.ordo-brand.small{ font-size:17px; padding:22px 20px 6px; letter-spacing:0.16em; color:#fff; }
.ordo-brand-mark{ color:var(--gold); margin-right:4px; }
.ordo-brand-sub{ color:var(--muted-2); font-size:11px; letter-spacing:0.16em; text-transform:uppercase; margin:6px 0 30px; }
.ordo-login-prompt{ color:var(--muted); font-size:13.5px; margin-bottom:20px; }
.ordo-user-grid{ display:grid; grid-template-columns:repeat(auto-fit, minmax(92px, 1fr)); gap:10px; }
.ordo-user-btn{ background:var(--surface-2); border:1px solid var(--line); border-radius:14px; padding:18px 10px; cursor:pointer;
  display:flex; flex-direction:column; align-items:center; gap:9px; color:var(--text); font-family:inherit;
  transition:border-color .16s, transform .16s, box-shadow .16s; }
.ordo-user-btn:hover{ border-color:var(--gold); transform:translateY(-2px); box-shadow:var(--shadow); }
.ordo-user-initial{ width:40px; height:40px; border-radius:50%; background:linear-gradient(145deg,var(--gold),var(--gold-dim));
  color:#fff; display:flex; align-items:center; justify-content:center; font-weight:600; font-size:16px; font-family:'Oswald',sans-serif; }
.ordo-user-initial.small{ width:32px; height:32px; font-size:13px; }
.ordo-user-name{ font-weight:600; font-size:13.5px; }
.ordo-pin-dots{ display:flex; justify-content:center; gap:14px; margin-bottom:18px; }
.ordo-pin-dot{ width:13px; height:13px; border-radius:50%; border:2px solid var(--line-2); transition:background .15s, border-color .15s, transform .15s; }
.ordo-pin-dot.filled{ background:var(--gold); border-color:var(--gold); transform:scale(1.12); }
.ordo-login-error{ color:var(--danger); font-size:12.5px; margin-bottom:12px; }
.ordo-keypad{ display:grid; grid-template-columns:repeat(3,1fr); gap:10px; }
.ordo-key{ background:var(--surface-2); border:1px solid var(--line); color:var(--text); border-radius:12px; padding:15px 0;
  font-size:17px; font-family:'JetBrains Mono',monospace; cursor:pointer; transition:background .13s, border-color .13s; }
.ordo-key:hover{ border-color:var(--gold); background:#fff; }
.ordo-key:active{ background:var(--gold); color:#fff; border-color:var(--gold); }
.ordo-key-ghost{ font-size:12px; font-family:'Inter',sans-serif; color:var(--muted-2); }

/* ---------- sidebar ---------- */
.ordo-sidebar{ width:232px; background:var(--sidebar); color:#fff; display:flex; flex-direction:column; flex-shrink:0; position:sticky; top:0; height:100vh; }
.ordo-nav{ display:flex; flex-direction:column; padding:14px 12px; gap:3px; flex:1; overflow-y:auto; }
.ordo-nav-btn{ text-align:left; background:none; border:none; color:#B9B5A6; padding:10px 13px; border-radius:9px; cursor:pointer;
  font-size:13.5px; font-family:inherit; position:relative; transition:background .14s, color .14s; }
.ordo-nav-btn:hover{ background:var(--sidebar-2); color:#fff; }
.ordo-nav-btn.active{ background:var(--sidebar-2); color:var(--gold); font-weight:600; }
.ordo-nav-btn.active::before{ content:''; position:absolute; left:0; top:9px; bottom:9px; width:3px; border-radius:0 3px 3px 0; background:var(--gold); }
.ordo-nav-sep{ margin:12px 13px 6px; font-size:10px; letter-spacing:0.14em; text-transform:uppercase; color:#5E5B50; }
.ordo-nav-link{ text-align:left; color:#8E8A7C; padding:8px 13px; border-radius:9px; font-size:12.5px; text-decoration:none;
  display:block; transition:background .14s, color .14s; }
.ordo-nav-link:hover{ background:var(--sidebar-2); color:#fff; }
.ordo-sidebar-footer{ padding:14px; border-top:1px solid rgba(255,255,255,0.08); }
.ordo-current-user{ display:flex; align-items:center; gap:9px; margin-bottom:11px; }
.ordo-cu-name{ font-size:13px; font-weight:600; color:#fff; }
.ordo-logout{ width:100%; background:none; border:1px solid rgba(255,255,255,0.16); color:#B9B5A6; padding:8px; border-radius:9px;
  cursor:pointer; font-size:12px; font-family:inherit; transition:border-color .14s, color .14s; }
.ordo-logout:hover{ border-color:var(--gold); color:var(--gold); }

/* ---------- main ---------- */
.ordo-main{ flex:1; padding:30px 36px 60px; overflow-y:auto; min-width:0; }
.ordo-page h1{ font-family:'Oswald',sans-serif; font-size:27px; font-weight:500; letter-spacing:0.02em; margin:0 0 3px; }
.ordo-sub{ color:var(--muted); font-size:13px; }
.ordo-page-head{ display:flex; justify-content:space-between; align-items:flex-start; gap:16px; margin-bottom:22px;
  padding-bottom:16px; border-bottom:1px solid var(--line); }
.ordo-section-title{ font-family:'Oswald',sans-serif; font-weight:500; font-size:12px; text-transform:uppercase;
  letter-spacing:0.13em; color:var(--muted); margin:30px 0 12px; }
.ordo-banner{ background:#FCF3DC; border:1px solid #E8D9A8; border-left:3px solid var(--gold); color:#6B5520;
  padding:11px 14px; border-radius:var(--r); font-size:12.5px; margin-bottom:18px; }

/* ---------- stats ---------- */
.ordo-stat-row{ display:grid; grid-template-columns:repeat(auto-fit, minmax(170px, 1fr)); gap:14px; }
.ordo-stat-card{ background:var(--surface); border:1px solid var(--line); border-radius:var(--r-lg); padding:17px 18px;
  box-shadow:var(--shadow-sm); transition:box-shadow .16s, transform .16s; }
.ordo-stat-card:hover{ box-shadow:var(--shadow); transform:translateY(-1px); }
.ordo-stat-label{ font-size:11px; color:var(--muted); text-transform:uppercase; letter-spacing:0.09em; font-weight:500; }
.ordo-stat-value{ font-size:27px; font-weight:600; font-family:'Oswald',sans-serif; margin-top:6px; letter-spacing:0.01em; }

/* ---------- pipeline ---------- */
.ordo-pipeline-bar{ display:grid; grid-template-columns:repeat(auto-fit,minmax(120px,1fr)); gap:10px; }
.ordo-pipeline-seg{ background:var(--surface); border:1px solid var(--line); border-radius:var(--r); padding:14px 10px;
  text-align:center; box-shadow:var(--shadow-sm); }
.ordo-pipeline-dot{ width:9px; height:9px; border-radius:50%; display:inline-block; margin-bottom:7px; }
.ordo-pipeline-label{ font-size:11px; color:var(--muted); }
.ordo-pipeline-count{ font-size:20px; font-weight:600; font-family:'Oswald',sans-serif; margin-top:2px; }

/* ---------- table ---------- */
.ordo-table{ width:100%; border-collapse:separate; border-spacing:0; background:var(--surface); border:1px solid var(--line);
  border-radius:var(--r-lg); overflow:hidden; box-shadow:var(--shadow-sm); }
.ordo-table th{ text-align:left; font-size:10.5px; text-transform:uppercase; letter-spacing:0.1em; color:var(--muted);
  font-weight:600; padding:11px 14px; background:var(--surface-2); border-bottom:1px solid var(--line); white-space:nowrap; }
.ordo-table td{ padding:11px 14px; border-bottom:1px solid var(--line); font-size:13.5px; vertical-align:middle; }
.ordo-table tr:last-child td{ border-bottom:none; }
.ordo-table-compact td, .ordo-table-compact th{ padding:7px 10px; font-size:12.5px; }
.ordo-table-scroll{ overflow-x:auto; border-radius:var(--r-lg); }
.ordo-clickable-row{ cursor:pointer; transition:background .13s; }
.ordo-clickable-row:hover{ background:var(--surface-2); }
.ordo-empty{ color:var(--muted-2); text-align:center; padding:28px; font-size:13px; }

.ordo-status-pill{ color:#fff; font-size:10.5px; padding:4px 11px; border-radius:20px; font-weight:600;
  letter-spacing:0.04em; white-space:nowrap; display:inline-block; }
.ordo-status-pill.large{ font-size:12px; padding:7px 16px; }

/* ---------- board ---------- */
.ordo-board{ display:flex; gap:13px; overflow-x:auto; padding-bottom:12px; }
.ordo-board-col{ min-width:210px; flex:1; }
.ordo-board-col-head{ display:flex; align-items:center; gap:7px; font-size:12px; font-weight:600; margin-bottom:11px;
  text-transform:uppercase; letter-spacing:0.06em; color:var(--muted); }
.ordo-board-count{ margin-left:auto; color:var(--muted-2); font-weight:500; background:var(--surface); border:1px solid var(--line);
  border-radius:20px; padding:1px 8px; font-size:11px; }
.ordo-board-cards{ display:flex; flex-direction:column; gap:9px; min-height:60px; }
.ordo-card{ background:var(--surface); border:1px solid var(--line); border-radius:var(--r); padding:12px 13px; cursor:pointer;
  box-shadow:var(--shadow-sm); transition:border-color .15s, transform .15s, box-shadow .15s; }
.ordo-card:hover{ border-color:var(--gold); transform:translateY(-2px); box-shadow:var(--shadow); }
.ordo-card-num{ font-size:11px; color:var(--muted-2); }
.ordo-card-client{ font-size:13.5px; font-weight:600; margin:3px 0; }
.ordo-card-value{ font-size:13px; color:var(--muted); }

/* ---------- forms ---------- */
.ordo-input{ width:100%; border:1px solid var(--line-2); border-radius:9px; padding:9px 11px; font-size:13.5px;
  font-family:'Inter',sans-serif; background:#fff; color:var(--text); transition:border-color .14s, box-shadow .14s; }
.ordo-input:hover{ border-color:var(--muted-2); }
.ordo-input:focus{ outline:none; border-color:var(--gold); box-shadow:0 0 0 3px rgba(198,169,106,0.18); }
.ordo-form-row{ display:flex; justify-content:space-between; align-items:center; margin-bottom:7px; }
.ordo-form-row label{ font-size:11.5px; color:var(--muted); font-weight:600; text-transform:uppercase; letter-spacing:0.07em; }
.ordo-toggle-group{ display:inline-flex; border:1px solid var(--line-2); border-radius:9px; overflow:hidden; }
.ordo-toggle-group button{ border:none; background:#fff; padding:7px 14px; font-size:12px; cursor:pointer; color:var(--muted);
  font-family:inherit; transition:background .14s, color .14s; }
.ordo-toggle-group button:hover{ background:var(--surface-2); }
.ordo-toggle-group button.active{ background:var(--gold); color:#fff; font-weight:600; }
.ordo-add-item-row{ display:flex; gap:10px; margin-top:12px; flex-wrap:wrap; }
.ordo-order-total{ text-align:right; font-size:15px; font-weight:600; margin-top:12px; font-family:'Oswald',sans-serif; }

/* ---------- buttons ---------- */
.ordo-btn-primary{ background:var(--text); color:#fff; border:none; border-radius:9px; padding:10px 18px; font-size:13px;
  font-weight:600; cursor:pointer; font-family:inherit; transition:background .15s, transform .15s; }
.ordo-btn-primary:hover:not(:disabled){ background:var(--gold); transform:translateY(-1px); }
.ordo-btn-primary:disabled{ opacity:0.35; cursor:not-allowed; }
.ordo-btn-ghost{ background:#fff; border:1px solid var(--line-2); border-radius:9px; padding:9px 15px; font-size:12.5px;
  cursor:pointer; color:var(--text); font-family:inherit; transition:border-color .14s, color .14s, background .14s; }
.ordo-btn-ghost:hover{ border-color:var(--gold); color:var(--gold-dim); }
.ordo-btn-ghost.small{ padding:5px 11px; font-size:11.5px; }
.ordo-icon-btn{ background:none; border:none; color:var(--muted-2); cursor:pointer; font-size:13px; padding:4px 6px;
  border-radius:6px; transition:color .14s, background .14s; }
.ordo-icon-btn:hover{ color:var(--danger); background:#FBEDED; }
.ordo-back-btn{ background:none; border:none; color:var(--muted); font-size:12.5px; cursor:pointer; margin-bottom:14px;
  padding:0; font-family:inherit; transition:color .14s; }
.ordo-back-btn:hover{ color:var(--gold-dim); }

/* ---------- status stepper ---------- */
.ordo-status-stepper{ display:flex; flex-wrap:wrap; gap:8px; align-items:center; }
.ordo-step{ border:1px solid var(--line-2); background:#fff; border-radius:20px; padding:8px 15px; font-size:12px;
  cursor:pointer; color:var(--muted); font-family:inherit; transition:border-color .14s, background .14s, color .14s; }
.ordo-step:hover{ border-color:var(--gold); color:var(--text); }
.ordo-step.done{ background:var(--surface-2); color:var(--text); border-color:var(--line); }
.ordo-step.active{ background:var(--text); border-color:var(--text); color:#fff; font-weight:600; }
.ordo-step.cancel{ margin-left:auto; color:var(--danger); border-color:#EACFCF; }
.ordo-step.cancel:hover{ background:#FBEDED; border-color:var(--danger); color:var(--danger); }

.ordo-doc-actions{ display:flex; gap:10px; margin-bottom:14px; flex-wrap:wrap; }

/* ---------- grids ---------- */
.ordo-assumptions-grid{ display:grid; grid-template-columns:repeat(auto-fit,minmax(210px,1fr)); gap:14px;
  background:var(--surface); border:1px solid var(--line); border-radius:var(--r-lg); padding:18px; box-shadow:var(--shadow-sm); }
.ordo-assumption label{ display:block; font-size:11px; color:var(--muted); margin-bottom:5px; font-weight:500; }

.ordo-client-list{ display:grid; grid-template-columns:repeat(auto-fit,minmax(320px,1fr)); gap:13px; }
.ordo-client-card{ background:var(--surface); border:1px solid var(--line); border-radius:var(--r-lg); padding:16px;
  display:flex; flex-direction:column; gap:9px; box-shadow:var(--shadow-sm); transition:box-shadow .16s; }
.ordo-client-card:hover{ box-shadow:var(--shadow); }
.ordo-client-name{ font-weight:600; font-family:'Oswald',sans-serif; font-size:15px; }
.ordo-client-grid{ display:grid; grid-template-columns:repeat(auto-fit,minmax(130px,1fr)); gap:8px; }

.ordo-pin-edit-row{ display:flex; gap:10px; align-items:center; flex-wrap:wrap; }
.ordo-hint{ font-size:12px; color:var(--muted); margin-top:10px; line-height:1.65; }
.ordo-ledger-form{ display:grid; grid-template-columns:auto 150px 150px minmax(200px,1fr) 130px auto; gap:9px; align-items:center;
  background:var(--surface); border:1px solid var(--line); border-radius:var(--r-lg); padding:14px; box-shadow:var(--shadow-sm); }
.ordo-link-btn{ background:none; border:none; padding:0; color:var(--gold-dim); text-decoration:underline; cursor:pointer;
  font-size:inherit; font-family:inherit; text-align:left; }
.ordo-link-btn:hover{ color:var(--text); }

/* ---------- modal ---------- */
.ordo-modal-overlay{ position:fixed; inset:0; background:rgba(20,21,15,0.6); backdrop-filter:blur(3px); display:flex;
  align-items:center; justify-content:center; z-index:50; padding:20px; animation:ordoFade .16s ease; }
@keyframes ordoFade{ from{ opacity:0 } to{ opacity:1 } }
.ordo-modal{ background:#fff; border-radius:16px; width:520px; max-width:100%; max-height:90vh; display:flex; flex-direction:column;
  box-shadow:var(--shadow-lg); animation:ordoRise .18s ease; }
@keyframes ordoRise{ from{ opacity:0; transform:translateY(10px) } to{ opacity:1; transform:none } }
.ordo-modal-wide{ width:760px; }
.ordo-doc-modal{ width:660px; }
.ordo-modal-head{ display:flex; justify-content:space-between; align-items:center; padding:18px 22px; border-bottom:1px solid var(--line); }
.ordo-modal-head h2{ font-family:'Oswald',sans-serif; font-size:17px; font-weight:500; margin:0; }
.ordo-modal-close{ background:none; border:none; font-size:16px; cursor:pointer; color:var(--muted-2); padding:4px 8px;
  border-radius:6px; transition:background .14s, color .14s; }
.ordo-modal-close:hover{ background:var(--surface-2); color:var(--text); }
.ordo-modal-body{ padding:20px 22px; overflow-y:auto; }
.ordo-modal-foot{ display:flex; justify-content:flex-end; gap:10px; padding:16px 22px; border-top:1px solid var(--line);
  background:var(--surface-2); border-radius:0 0 16px 16px; }

/* ---------- document paper ---------- */
.ordo-doc-paper{ padding:30px 34px; font-size:13px; }
.ordo-doc-header{ display:flex; justify-content:space-between; gap:20px; border-bottom:2px solid var(--text);
  padding-bottom:16px; margin-bottom:18px; }
.ordo-doc-company{ font-family:'Oswald',sans-serif; font-weight:600; font-size:22px; letter-spacing:0.06em; }
.ordo-doc-tagline{ color:var(--muted); font-size:11.5px; margin-bottom:8px; }
.ordo-doc-line{ font-size:11.5px; color:var(--muted); }
.ordo-doc-meta{ text-align:right; white-space:nowrap; }
.ordo-doc-type{ font-family:'Oswald',sans-serif; font-weight:600; letter-spacing:0.14em; color:var(--gold-dim); font-size:14px; }
.ordo-doc-label{ font-size:10px; text-transform:uppercase; color:var(--muted-2); letter-spacing:0.11em; margin-bottom:3px; }
.ordo-doc-bill{ margin-bottom:18px; }
.ordo-doc-table{ width:100%; border-collapse:collapse; }
.ordo-doc-table th{ text-align:left; border-bottom:1px solid var(--text); padding:7px 4px; font-size:10.5px;
  text-transform:uppercase; letter-spacing:0.08em; color:var(--muted); }
.ordo-doc-table td{ padding:8px 4px; border-bottom:1px solid var(--line); }
.ordo-doc-totals{ text-align:right; margin-top:14px; font-size:13px; }
.ordo-doc-totals .grand{ font-weight:700; font-size:16px; margin-top:5px; font-family:'Oswald',sans-serif; }
.ordo-doc-bank{ margin-top:22px; border-top:1px solid var(--line); padding-top:12px; font-size:12px; }

/* ---------- responsive ---------- */
@media (max-width:1150px){
  .ordo-ledger-form{ grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); }
}

@media (max-width:900px){
  .ordo-app{ flex-direction:column; }
  .ordo-sidebar{ width:100%; height:auto; position:static; }
  .ordo-nav{ flex-direction:row; overflow-x:auto; padding:10px; }
  .ordo-nav-btn{ white-space:nowrap; }
  .ordo-nav-btn.active::before{ display:none; }
  .ordo-nav-sep,.ordo-nav-link{ display:none; }
  .ordo-sidebar-footer{ display:flex; align-items:center; justify-content:space-between; gap:12px; }
  .ordo-current-user{ margin-bottom:0; }
  .ordo-logout{ width:auto; padding:8px 14px; }
  .ordo-main{ padding:20px 16px 40px; }
  .ordo-ledger-form{ grid-template-columns:1fr; }
}

@media print{
  .no-print{ display:none !important; }
  .ordo-modal-overlay{ position:static; background:none; backdrop-filter:none; padding:0; }
  .ordo-modal{ box-shadow:none; width:auto; max-height:none; }
}
`;
